### 1. HMM Brief
- Hidden Markov model is a statistical Markov model in which the system being modeled is assumed to be a Markov process — call it X — with unobservable ("hidden") states. As part of the definition, HMM requires that there be an observable process Y whose outcomes are "influenced" by the outcomes of X in a known way. 

- Since X cannot be observed directly, the goal is to learn about X by observing Y.
  HMM has an additional requirement that the outcome of Y at time {\displaystyle t=t_{0}}{\displaystyle t=t_{0}}    must be "influenced" exclusively by the outcome of X at: $$t=t_{0}$$

  must be "influenced" exclusively by the outcome of X at 
   $$t=t_{0}$$

  and that the outcomes of X and Y at
   $$t<t_{0}$$

  must not affect the outcome of Y at 
   $$t=t_{0}$$

- Given a Hidden Markov Model (HMM), we want to calculate the probability of a state at a certain time, given some evidence via some sequence of emissions. Let us assume the following [HMM](https://en.wikipedia.org/wiki/Hidden_Markov_model) as described in Chapter 9.2 of Manning and Schütze (1999)

[ReadMe](http://damir.cavar.me/pynotebooks/Python_Tutorial_HMM.html)

### 2. Implications
- Reinforce Learning, Temporal Pattern Recognition
- Speech, hand-writing, Gesture recognition, part-of-speech tagging, musical score following, pratial dischareges and bioinformatics

### 3. Implementation

In [5]:
import numpy as np

In [6]:
stateMatrix = np.matrix("0.7 0.3; 0.5 0.5")

In [7]:
stateMatrix

matrix([[0.7, 0.3],
        [0.5, 0.5]])

In [8]:
stateMatrix.dot(stateMatrix)

matrix([[0.64, 0.36],
        [0.6 , 0.4 ]])

In [9]:
emissionMatrix = np.matrix("0.6 0.1 0.3; 0.1 0.7 0.2")

In [10]:
emissionMatrix

matrix([[0.6, 0.1, 0.3],
        [0.1, 0.7, 0.2]])

In [11]:
initialMatrix = np.matrix("1 0")

In [12]:
from nltk.corpus import treebank

In [13]:
from nltk.tag import hmm

In [14]:
trainer = hmm.HiddenMarkovModelTrainer()